### ISSUE TITLE
AcquireTokenByRefreshTokenAsync is removed

### ISSUE THREAD

**Issue by MikeStall** [microsoftgraph/aspnet-webhooks-rest-sample#13]
This calls AcquireTokenByRefreshTokenAsync , but that API was removed (see https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/446 ) 

So this won't compile with the latest ADAL nugget packages.  Can you make an update to get it to compile?

 
Usage at: 
https://github.com/microsoftgraph/aspnet-webhooks-rest-sample/blob/master/GraphWebhooks/Controllers/Utils/AuthHelper.cs#L33

**Comment by DianeD** [comment]
Hi @MikeStall . Thanks for reporting this. Looking into it now.

**Comment by DianeD** [comment]
Thanks @MikeStall ! Updated to Adal v3. Relies on the ADAL token cache to silently handle refresh flow. For more information about customizing the cache, see http://www.cloudidentity.com/blog/2014/07/09/the-new-token-cache-in-adal-v2/

**Comment by Mahendran** [comment]
Hi DianeD,
 I am creating Daemon(app-only) service and acquired the access token using following API AcquireTokenAsync(string resource, IClientAssertionCertificate clientCertificate);

Unfortunately I am unable to find the API to refresh the access token using TokenCache.

Could you please help me to solve the problem.

Thanks
Mahendran
