### ISSUE TITLE
impersonation

### ISSUE THREAD

**Issue by lotusinriver** [microsoftgraph/aspnet-webhooks-rest-sample#17]
Can the login user impersonate as other users and subscribe other user's events?

**Comment by jasonjoh** [comment]
No. Subscriptions are created via the Microsoft Graph API, which uses OAuth bearer tokens. The app in this case is always acting on the logged-in user's behalf.

You could modify this to use app-only authentication, which would require a tenant admin to consent to the app. It could then have permission to all user's in the tenant and subscribe to any of them.
