### ISSUE TITLE
what kind of permission need to set for this application ?

### ISSUE THREAD

**Issue by asith-w** [microsoftgraph/aspnet-webhooks-rest-sample#23]
what kind of permission need to set for this application.? i am getting error when loggin office 365 account

![image](https://user-images.githubusercontent.com/5784846/41849416-77a1a702-789e-11e8-8ef2-444c56bc21f4.png)

**Comment by jasonjoh** [comment]
You do not set permissions for this application in the Azure portal. The app is registered in the App Registration Portal instead. Registration instructions are in the README. The app requests permissions dynamically, the scopes are set here: https://github.com/microsoftgraph/aspnet-webhooks-rest-sample/blob/85145615f4ee3f49f43a552637e956e82b9696d4/GraphWebhooks/PrivateSettings.example.config#L6
