### ISSUE TITLE
An error occurred while processing your request.

### ISSUE THREAD

**Issue by asith-w** [microsoftgraph/aspnet-webhooks-rest-sample#24]
i am getting following error

![image](https://user-images.githubusercontent.com/5784846/42272932-4a130818-7fa5-11e8-9868-e5d1078bd170.png)

even if i add tenant  id for the    _Authority_  ,   _cca.AcquireTokenByAuthorizationCodeAsync(code, Scopes);_ calls for common api.
is there way to fix this ?

**Comment by jasonjoh** [comment]
How did you register your application? What kind of account are you logging in with (Office 365 or Outlook.com?)

**Comment by asith-w** [comment]
i am using office 365 account and register through https://apps.dev.microsoft.com. am i doing wrong ?

**Comment by jasonjoh** [comment]
No, that should work. What is your value for `Authority` in Startup.Auth.cs?

**Comment by jasonjoh** [comment]
Also, when you login to apps.dev.microsoft.com, do you have multiple "Add an app" buttons? If so, is your app registration under "Converged" or something else?

**Comment by asith-w** [comment]
used apps.dev.microsoft.com instead of azure portal and fixed the issue as below 
thanks @jasonjoh 
 
![csapture](https://user-images.githubusercontent.com/5784846/43833640-17e5b080-9b29-11e8-99d7-0c65faa154be.PNG)
