### ISSUE TITLE
Create; Exception: [A task was canceled.] Inner error

### ISSUE THREAD

**Issue by salmanme123** [microsoftgraph/aspnet-webhooks-rest-sample#25]
Microsoft Graph WebHooks was working fine till yesterday but i got problem today while creating subscription 

> Code: ExtensionError Message: Operation: Create; Exception: [A task
> was canceled.] Inner error

Following is code

```
    [Authorize]
        public async Task<ActionResult> CreateSubscription()
        {
            string baseUrl = $"{Request.Url.Scheme}://{Request.Url.Authority}";

            try
            {
                var subscription = await SubscriptionHelper.CreateSubscription(baseUrl);

                SubscriptionViewModel viewModel = new SubscriptionViewModel()
                {
                    Subscription = subscription
                };

                return View("Subscription", viewModel);
            }
            catch (Exception e)
            {
                ViewBag.Message = BuildErrorMessage(e);
                return View("Error", e);
            }
        }
```
Following is the stack trace

> "   at Microsoft.Graph.HttpProvider.<SendAsync>d__19.MoveNext()\r\n---
> End of stack trace from previous location where exception was thrown
> ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
> task)\r\n   at
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
> task)\r\n   at
> Microsoft.Graph.BaseRequest.<SendRequestAsync>d__36.MoveNext()\r\n---
> End of stack trace from previous location where exception was thrown
> ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
> task)\r\n   at
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
> task)\r\n   at
> Microsoft.Graph.BaseRequest.<SendAsync>d__32`1.MoveNext()\r\n--- End
> of stack trace from previous location where exception was thrown
> ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
> task)\r\n   at
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
> task)\r\n   at
> System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at
> GraphWebhooks.Helpers.SubscriptionHelper.<CreateSubscription>d__2.MoveNext()
> in
> C:\\Users\\alias\\Downloads\\aspnet-webhooks-rest-sample-master\\aspnet-webhooks-rest-sample-master\\GraphWebhooks\\Helpers\\SubscriptionHelper.cs:line
> 32\r\n--- End of stack trace from previous location where exception
> was thrown ---\r\n   at
> System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
> task)\r\n   at
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
> task)\r\n   at
> System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at
> GraphWebhooks.Controllers.SubscriptionController.<CreateSubscription>d__1.MoveNext()
> in
> C:\\Users\\alias\\Downloads\\aspnet-webhooks-rest-sample-master\\aspnet-webhooks-rest-sample-master\\GraphWebhooks\\Controllers\\SubscriptionController.cs:line
> 30"

Following is the image
https://i.stack.imgur.com/RDESj.png

https://i.stack.imgur.com/AviYX.png
Please Help me out as soon as possible i have to publish this task

**Comment by baywet** [comment]
Hi @salmanme123 
Sorry about the late reply, we're working on new samples and suggest you try those out instead. https://github.com/microsoftgraph/csharp-webhook-with-resource-data
