### ISSUE TITLE
Issue while sign-in to application on organization id

### ISSUE THREAD

**Issue by ikhaleel** [microsoftgraph/aspnet-webhooks-rest-sample#26]
AADSTS90130: Application 'f560adfe-a116-4c52-b897-af5b2ca5e8c8' (WebhooksAPI) is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint. Trace ID: a733c9b9-bcd6-4a58-a298-a7da35739800 Correlation ID: dd7c866d-7f6e-4d01-9183-8d005bd70f27

Authority: $"https://login.microsoftonline.com/{tenanct}/v2.0".

Please help ,I'm struck for long time. I changed multi-tenant to true ,but still no luck

**Comment by jasonjoh** [comment]
This error indicates a problem with your app registration. Please be sure that you are registering your app in https://apps.dev.microsoft.com. **Also**, if when you login to https://apps.dev.microsoft.com you see more than one **Add an app** button, be sure to use the one for **Converged apps**.

**Comment by ikhaleel** [comment]
Thanks a lot jasonjoh :). Its working now. I registered by app under converged apps. Previously i did using portal.azure.com.
