### ISSUE TITLE
Not getting any callbacks

### ISSUE THREAD

**Issue by ghost** [microsoftgraph/aspnet-webhooks-rest-sample#3]
I’m trying to setup a similar web app that receives Graph notifications when the logged in user receives new emails. The app has Mail.Read permission (can access me/messages successfully) and the subscription seems to be created, or at least I get this response back from the Graph:

`
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#subscriptions/$entity",
"id":"<hidden>",
"resource":"me/messages",
"changeType":"created",
"clientState":" subscription-identifier",
"notificationUrl":"<my-public-api-endpoint>",
"expirationDateTime":"2016-07 -13T18:23:45.9356913Z"},
"status":201,
…
"statusText":"Created"}
`

but I don’t get any notification / calls to my API when the user that created the subscription receives new emails. Is there any way to monitor existing subscriptions or see when POST calls are made by Graph? Or what would be a good approach to debug this? The app itself is hosted on Azure, is there anything I need to enable in app settings for this to work? I assume CORS is not required.

The code in my API controller, handling POSTs, just logs incoming calls – it gets called when creating the subscription, but doesn’t receive any notifications:

```
public async Task<HttpResponseMessage> Post()
        {
            string validationToken = Request.GetQueryNameValuePairs()
                .SingleOrDefault(x => x.Key == "validationToken").Value;
            if (validationToken != null)
            {
                Trace.Write("Controller -- received validation token:" + validationToken + "\n");
                var response = Request.CreateResponse(HttpStatusCode.OK);
                response.Content = new StringContent(validationToken, Encoding.UTF8, "text/plain");
                return response;
            }
            else
            {
              Trace.Write("Controller: POST\n"); // Never called

              var incomingData = await Request.Content.ReadAsAsync<JObject>();
              if (incomingData != null)
              {
                  Trace.Write("Controller data:" + incomingData.ToString());
              }
            }
            return Request.CreateResponse(HttpStatusCode.OK, "OK");
        }
```

**Comment by DianeD** [comment]
Hi @rogerthealien . Sorry for the delayed response. There isn't a way to monitor calls from the Microsoft Graph side, but you can open a [StackOverflow issue tagged with MicrosoftGraph](https://stackoverflow.com/questions/tagged/MicrosoftGraph) if you aren't receiving notifications or if you have questions about a subscription. Please include the subscription ID and its creation time. I added this info to the readme, so I'm closing the issue. Thanks
