### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by oyvindk** [microsoftgraph/aspnet-webhooks-rest-sample#35]
The page at https://docs.microsoft.com/en-us/samples/microsoftgraph/aspnet-webhooks-rest-sample/microsoft-graph-aspnet-webhooks/ has some links to files in a repo that has been moved. The repo is now at https://github.com/microsoftgraph/aspnet-webhooks-rest-sample/tree/master/GraphWebhooks/. The broken links are under the heading "Key components of the sample".

**Comment by jasonjoh** [comment]
Thanks @oyvindk. The first link you sent is apparently just publishing the README from this repo, which contains relative links to those files. They of course work when reading the README on GitHub. But during publication to Docs, they've made them relative to the docs.microsoft.com/samples site, which is broken. The easy fix here would be to remove the links or make them absolute, but I'm going to discuss with the folks implementing the sample browser to evaluate this problem. I can't imagine it's just this one sample :).
