### ISSUE TITLE
Confusing/erroneous instructions, plus sign-in loop

### ISSUE THREAD

**Issue by elegault** [microsoftgraph/aspnet-webhooks-rest-sample#7]
In the section where it asks to use the Office 365 app registration tool, the parameters for the tool do not match the parameters in the instructions.  For example, the properties on the main page for a registered app in Azure AD only show:

- Display Name
- Application Type
- Home Page
- Application ID
- Object ID

The bigger problem though is that the instructions state to "copy and store the returned Client ID and Client Secret values".  Where is Client Secret?  Is it Object ID?  Does Client ID = Application ID?  Those are the values I've used for the keys in the web.config file.  However, when I run the app I get a repeating loop: Create Registration -> Signin -> Create Registration, etc.  It never gets to the stage that displays the 'Watch for notifications' button.  I am using ngrok and have edited web.config accordingly:

    <add key="ida:NotificationUrl" value="https://4ca0d7a8.ngrok.io:44300/notification/listen" />

Does that URL have to be used in the app registration parameters? What am I doing wrong?

Also, is it not required that permissions to Microsoft Graph be added to the app via the registration page in Azure?  Wouldn't "Read mail in all mailboxes" be required?

**Comment by elegault** [comment]
I tried creating the app via the App Registration Portal instead (which does have a client secret) and I at least got a little further and can authenticate.  I also fixed the problem with my NotificationUrl key containing the port number (44300), so I removed that.  However now when I login via Firefox, it simply returns to the login screen instead of the main app page.  With other browsers I can login, but clicking the "Create subscription" button attempts to navigate to the below URL but it never gets reached and is always "Working...":

https://login.microsoftonline.com/common/oauth2/authorize?client_id=12346328-22fd-42d2-9b6b-b353b9403136&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dVvxlwBTtDLgte622W2jVkBOZXj9xsCA318ZiHFnazwR_9R0LQxUlGqwbRHaOP4UK2-5f-GNON_kX_WPI5Uhg71aQIjc0Rbzlf7-WM-4-_75CI2mw5RK-lQ1r7qduU6UwN8G8SPgwAGvN8-Y5ABqhrmfQx_jTDHuz10ih2l7_FFg&nonce=636152919460533729.MDgzNzY3MDUtYjhkZS00MzE2LThjNWUtMDBiYmQ4MzdhOTI2OWI1NjA0YmQtOTQ3My00NDZhLTg1ODctZWRlZDIyYTQzNjRj&redirect_uri=https%3a%2f%2flocalhost%3a44300%2f&post_logout_redirect_uri=https%3a%2f%2flocalhost%3a44300

FYI, my http port is 54089, my https port is 44300. So I ran ngrok with:

ngrok http 54089 -host-header=localhost:54089

Is only localhost and the https port number used in the manifest/app keys?  Not the ngrok url and tunnel?

BTW: the screenshot in step 6 has the wrong port number (51825), it should be 21942 according to the two previous screenshots.

**Comment by elegault** [comment]
My apologies - I was testing the URL with /common/v2.0 as I thought that was an omissions It works fine now after I stuck with the default URL, and also after I revoked the app permissions and re-authed it since I added Mail.Read permissions after the fact.  Regardless, there's definitely a few areas in the doc that could be clarified to save other dum-dums like myself from making stupid mistakes and assumptions.  :-)

**Comment by DianeD** [comment]
Hi @elegault . Thanks for your feedback! Sorry--I started updating the instructions for the new portal last week, but not in time for your run. I think I addressed all the issues you describe here. Thanks again for the detailed report!
