### ISSUE TITLE
Microsoft Graph is not sending notifications

### ISSUE THREAD

**Issue by johnthomasp** [microsoftgraph/aspnet-webhooks-rest-sample#8]
Microsoft Graph is not sending notifications for the subscription created.

**Comment by DianeD** [comment]
Hi @johnthomasp . Thanks for reporting this. I'm checking with the product team to see what info we need from you to help resolve your issue.

Are you using ngrok? Did you use the [web interface](http://127.0.0.1:4040) to inspect the HTTP traffic, but get no notifications coming through?

**Comment by johnthomasp** [comment]
Hi Diane,
Thank you for reaching out, The issue is resolved, We were facing the issue because the token had expired.

**Comment by DianeD** [comment]
Great, thanks for letting us know!
